# LogMich - A Trivial Logging Library
# Copyright (C) 2020 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    clang-10
    g++-10
    cmake
    build-essential
    libfmt-dev

.build_project_template: &build_project
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DBUILD_EXTRA=ON -DBUILD_EDITOR=ON
    - make -k VERBOSE=1
    - make test VERBOSE=1 ARGS="-V"

build:gcc:release:
  <<: *build_project
  variables:
    CXX: "g++-10"
    BUILD_TYPE: "Release"

build:clang:release:
  <<: *build_project
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Release"

build:gcc:debug:
  <<: *build_project
  variables:
    CXX: "g++-10"
    BUILD_TYPE: "Debug"

build:clang:debug:
  <<: *build_project
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Debug"

build:clang-tidy:
  <<: *build_project
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Debug"
    CLANG_TIDY: "ON"

# EOF #
